name: Auto Blog Publisher

on:
  schedule:
    - cron: "0 13 * * *"   # 每天北京时间21:00
  workflow_dispatch:        # 支持手动运行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install openai==0.28 requests pandas

      - name: Run Auto Blog Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_APP_PASS: ${{ secrets.WP_APP_PASS }}
          WP_URL: ${{ secrets.WP_URL }}
        run: |
          python blog.py
